# Generated by Django 2.2.7 on 2019-12-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20191117_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
