# Generated by Django 2.2.7 on 2019-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_remove_profile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='social.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='header_picture',
            field=models.ImageField(default='img/headerpictures/default-header-picture.png', upload_to='img/headerpictures/'),
        ),
    ]
