# Generated by Django 3.0.6 on 2020-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20200511_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='social.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='header_picture',
            field=models.ImageField(default='img/headerpictures/default-header-picture.png', upload_to='img/headerpictures/'),
        ),
    ]
